### ISSUE TITLE
message gets cut. when more then 32k bytes sent

### ISSUE THREAD

**Issue by darkfriend77** [godsharp/GodSharp.Socket#9]
Sending bigger buffers then 32k byte

usually around byte[32541] ...

ProtoBuf.ProtoException
  HResult=0x80131500
  Nachricht = Unexpected end-group in source data; this usually means the source data is corrupt
  Quelle = protobuf-net
  Stapelüberwachung:
   at ProtoBuf.ProtoReader.ReadFieldHeader() in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 672
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 722
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 590
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in C:\code\protobuf-net\src\protobuf-net\Serializer.cs:line 68
   at SabberStoneCommon.Contract.DataPacketBuilder.Deserialize(Byte[] buffer) in C:\Users\admin\Source\Repos\SabberStoneGodSharp\SabberStoneCommon\Contract\DataPacket.cs:line 22
   at SabberStoneClient.Client.GameClient.OnReceived(NetClientReceivedEventArgs`1 c) in C:\Users\admin\Source\Repos\SabberStoneGodSharp\SabberStoneClient\Client\GameClient.cs:line 123
   at GodSharp.Sockets.Abstractions.NetListener`1.ReceivedCallback(IAsyncResult result)

**Comment by seayxu** [comment]
Not found this problem,it can received 65535 bytes.
